ProjetHotel/Models/Hotel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace ProjetHotel.Models
{
    public class Hotel
    {
        [DisplayName("Hotel")]
        [Required]
        public int IdHotel { get; set; }
        [DisplayName("Nom de L'Hotel")]
        [Required]
        public string Nom { get; set; }
        [DisplayName("Nombre de Chambre")]
        [Required]
        public int NBChambre { get; set; }
        [DisplayName("Pays")]
        [Required]
        public string Pays { get; set; }
        [DisplayName("Ville")]
        [Required]
        public string Ville { get; set; }
    }
}

ProjetHotel/Controllers/CalendarController.cs
using Microsoft.AspNetCore.Mvc;
using ProjetHotel.Infrastructure;
using ProjetHotel.Models;
using ProjetHotelBLL.Services;
using ProjetHotel.Models.Mapper;
namespace ProjetHotel.Controllers
{
    public class CalendarController : Controller
    {
        private readonly SessionManager _sessionManager;
        private readonly ReservationService _reservationService;
        public CalendarController(SessionManager sessionManager, ReservationService reservationService)
        {
            _sessionManager = sessionManager;
            _reservationService = reservationService;
        }


        public IActionResult Calendar()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Calendar([FromForm]ReservationForm reservation)
        {
            // TODO : 
            // - Obtenir l'id la personne (session)

            if (_sessionManager.User == null)
            {
                return RedirectToAction("Login", "Client");
            }
            reservation.IdClient = _sessionManager.User.IdClient;

            // - Obtenir l'id de l'hotel
            int IdHotel;
            Int32.TryParse(ControllerContext.RouteData.Values["id"].ToString(),out IdHotel );
            reservation.IdHotel = IdHotel;

            Reservation reservation1 = _reservationService.Insert(
                reservation.DateDepart,
                reservation.DateArrivee,
                reservation.IdHotel,
                reservation.IdClient

            ).ToModel();


            // - Créer la reservation

            // Et cela dans la BLL ;) 

            return View();
        }
    }
}

ProjetHotel/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ProjetHotel.Infrastructure;
using ProjetHotel.Models;
using ProjetHotel.Models.Mapper;
using ProjetHotelBLL.Services;
using System.Diagnostics;

namespace ProjetHotel.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly SessionManager _sessionManager;



        private HotelService hotelService;
        private ReservationService reservationService;




        public HomeController(ILogger<HomeController> logger, HotelService hotelService, SessionManager sessionManager, ReservationService reservationService)
        {
            _logger = logger;
            this.hotelService = hotelService;
            _sessionManager = sessionManager;
            this.reservationService = reservationService;


        }

        public IActionResult Index()
        {
            IEnumerable<Hotel> hotel = hotelService.GetAll()
                                                       .Select(b => b.ToModel())
                                                       .OrderBy(b => b.Nom);
            return View(hotel);
        }



        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public IActionResult MesReservation()
        {
            int? idClient = _sessionManager.User?.IdClient;

            if (idClient is null)
            {
                return RedirectToAction("Login", "Client");
            }


            IEnumerable<Reservation> reservation = reservationService.GetByIdClient((int)idClient)
                                                       .Select(c => c.ToModel())
                                                       .OrderBy(c => c.DateDepart);
            return View(reservation);
        }

        public IActionResult Delete(int id)
        {
            //Console.WriteLine(id);
            //if(id == 1)
            //{
            //    RedirectToAction("Index");
            //}
            bool deleted = reservationService.Delete(id);
            //if (deleted)
            //{
                return RedirectToAction("MesReservation", "Home");

            //}
            //else
            //{
            //    Console.WriteLine($"Deleted: {deleted}");
            //    return RedirectToAction("Index");

            //}
        }
    }
}

ProjetHotel/Views/Home/Hotel.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

ProjetHotel/Views/Home/Index.cshtml
@using ProjetHotel.Infrastructure

@* Ceci est une injection de dépendence, dans un fichier Razor *@
@inject SessionManager sessionManager

@model IEnumerable<ProjetHotel.Models.Hotel>

@{
    ViewData["Title"] = "Hotel list";
}


<div class="text-center">

    <h1 class="display-3">Welcome To The ProjetHotel</h1>
</div>
@*<h2>@(string.IsNullOrWhiteSpace(sessionManager.Pseudo) ? "Welcome" : sessionManager.Pseudo)</h2>*@
<h2>@(sessionManager?.User?.Pseudo ?? "Welcome")</h2>

<table class="table table-striped">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdHotel)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nom)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NBChambre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pays)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ville)
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdHotel)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nom)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NBChambre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Pays)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ville)
            </td>

            <td>
                <a class ="text-primary " asp-controller="Calendar" asp-action="Calendar" asp-route-id ="@item.IdHotel" >
                    <i class="btn btn-primary"> Réserver </i>
                </a>

            </td>
        </tr>
}
    </tbody>
</table>_
<img src="https://assets.anantara.com/image/upload/q_auto,f_auto/media/minor/anantara/images/anantara-palazzo-naiadi-rome/sneak-peak/anantara_palazzo_naiadi_rome_hotel_new_opening_750x405.jpg" alt="Hotel" class="mx-auto d-block">

ProjetHotel/Views/Home/MesReservation.cshtml
@using ProjetHotel.Infrastructure

@model IEnumerable<ProjetHotel.Models.Reservation>

@{
    ViewData["Title"] = "Mes Reservation";
}


<div class="text-center">
    <h1 class="display-4">Mes Reservation</h1>
</div>

<table class="table table-striped">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DateArrivee)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateDepart)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NBNuit)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdHotel)
            </th>
        </tr>
    </thead>
    <tbody>

@foreach (var item in Model) 
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.DateArrivee)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DateDepart)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NBNuit)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.IdHotel)
                    </td>
                    <td>
                        <a class = "btn btn-outline-dark" asp-action="Delete" asp-controller="Home" asp-route-id=@item.IdReservation >Supprimer</a>
                    </td>
                </tr>
            }
    </tbody>
</table>_
<img src="http://www.hervekabla.com/wordpress/wp-content/uploads/2019/10/ROOM_331_001-1.2-1024x576.jpg" alt="Hotel" class="mx-auto d-block" >